int ALLOW = 1;
int DENY = 0;

int policy(int port) {
    int allowed_port = ??(16);
    int low = ??(16);
    int high = ??(16);

    if (port == allowed_port) return ALLOW;
    if (low <= port && port <= high) return ALLOW;
    return DENY;
}

harness void main() {
assert policy(443) == DENY;
assert policy(80) == ALLOW;
assert policy(8017) == ALLOW;
assert policy(8018) == ALLOW;
assert policy(8014) == ALLOW;
assert policy(8011) == ALLOW;
assert policy(8003) == DENY;
assert policy(8012) == ALLOW;
assert policy(8004) == DENY;
assert policy(8008) == DENY;
assert policy(8005) == DENY;
assert policy(8001) == DENY;
assert policy(8020) == DENY;
assert policy(8002) == DENY;
assert policy(8007) == DENY;
assert policy(8015) == ALLOW;
assert policy(8019) == ALLOW;
assert policy(8009) == DENY;
assert policy(8016) == ALLOW;
assert policy(8013) == ALLOW;
assert policy(8000) == DENY;
assert policy(8006) == DENY;
assert policy(8010) == DENY;
}
